name: Espresso CI

on:
  push:
  workflow_dispatch:

jobs:
  execute_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK system image
        run: |
          sdkmanager --install "system-images;android-33;google_apis;x86_64"

      - name: Create Device
        run: |
          echo no | avdmanager create avd -n "Pixel_4_API_33" -k "system-images;android-33;google_apis;x86_64" -d pixel_4


      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android Emulator and execute tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_4
          script: |
            chmod +x ./gradlew
            ./gradlew clean
            ./gradlew connectedDebugAndroidTest

      - name: Upload Espresso test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: espresso-test-reports
          path: app/build/reports
