name: Espresso CI

on:
  push:
  workflow_dispatch:

jobs:
  execute_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Enable KVM for hardware acceleration
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo adduser $USER libvirt
          sudo adduser $USER kvm

      - name: Run Android Emulator and execute tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_4
          script: |
            chmod +x ./gradlew
            ./gradlew clean
            ./gradlew connectedDebugAndroidTest

      - name: Upload Espresso test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: espresso-test-reports
          path: app/build/reports
